language: node_js
node_js:
  - "0.10"
  - "0.8"

before_install:
  - npm update -g npm

before_script:
  - rm -R node_modules/model
  - rm -R node_modules/utilities
  - npm install https://github.com/mde/model/archive/master.tar.gz
  - npm install https://github.com/mde/utilities/archive/master.tar.gz

script: node_modules/jake/bin/cli.js test --trace
